import { PartnershipAgreementType } from "public/locales/terms-and-conditions/introducing-broker/types";

export default {
  PartnershipAgreement: "Partnership Agreement",
  ThePresentAgreement:
    "The present Agreement is made between Zetradex Holding ltd, hereinafter referred to as “the Company,” and the Partner. The Parties hereby agree to the following:",
  General_1: "General conditions, terminology",
  APartner_1_1:
    "A Partner, also known as an Introducing broker (IB) is an independent legal or individual person or an entrepreneur who undertakes, in the interests of the Company, to advertise, promote the Сompany’s services and represent its interests in order to attract clients and receive regular rewards , which will depend on the volume of services provided to the affiliated client and the money they spent with that.",
  Affiliated_1_2:
    "Affiliated client is an independent third-party person referred by the partner with help of special unique code/link, generated by the Company for every single partner, with the aim of receiving agent commissions and additional earnings, according to the Agreement.",
  TheCompany_1_3:
    "The Company and the Partner undertake obligations to attract Customers who would carry out trading operations with the instruments the Company offers.",
  ThePartner_1_4:
    "The Partner undertakes rights and obligations described in this Agreement with regard to the attraction of Customers for entering into brokerage service contracts with the Company. The Partner also undertakes other rights and obligations hereinafter set forth. Honoring the commitments stipulated in the present Agreement, the Partner attracts Customers for the Company on its behalf.",
  ThePartner_1_5:
    "The Partner unconditionally acknowledges that all Customers attracted are the Company’s Customers, and can't be referred to another Companies in the future by the Partner’s decision.",
  TheCompany_1_6:
    "The Company has a right to request confirmation of any information the Partner provides during registration for the affiliate program. For this purpose, the Company shall be entitled to request a scanned copy or a notarized copy of the Partner's ID document, at the Company's discretion.",
  IfThePartner_1_7:
    "If the Partner has not received the Company's request for a scanned copy or a notarized copy of the ID document, the verification of the affiliate account shall be deemed non obligatory. However, the Company reserves the right to restrict access of non-verified accounts to certain services. In this case, the Partner may optionally pass the verification procedure.",
  InTheEvent_1_8:
    "In the event that any information provided by the Partner during registration (name, residential address or telephone number) changes, the Partner must immediately inform the Partner Relations Department of the Company about these changes and request that the Company updates the information.",
  ThePartner_1_9:
    "The Partner acknowledges and agrees that any information provided during registration for the affiliate program may be employed by the Company in an anti-money laundering campaign.",
  ThePartner_1_10:
    "The Partner is responsible for the authenticity of their ID documents (copies included). The Partner acknowledges the Company's right to contact law enforcement agencies of the country where the ID document was issued to confirm its authenticity if it is questionable. Should the ID document be found to be a forgery, the Company shall be entitled to bring the Partner to justice in accordance with legislation in the country where the ID document was issued.",
  RelationshipWithCustomers: "Relationship with Customers",
  ThePartner_2_1:
    "The Partner may provide advertising of the Company referring to the corresponding section of the Company’s website and information confirmed to be authentic by the Company to prospective Customers.",
  ThePartner_2_2:
    "The Partner shall provide Customers with essential reliable information relevant to entering into brokerage service contracts with the Company and explanations regarding the content of the contracts and the Company’s services.",
  Providing_2_3:
    "Providing recommendations and information to motivate a Customer to trade is not part of the Company’s service plan. In exceptional cases, the Company has a right to provide information, recommendations and advice to a Customer at its discretion, however, the Company shall not bear responsibility for the consequences of such recommendations.",
  ThePartner_2_4:
    "The Partner shall refrain from giving a Customer recommendations or advice concerning trading operations on the trading account. In case the Partner does not comply with this, the Company shall not bear responsibility for the consequences of the recommendations or advice provided in the context of allegations of losses resulting from compliance with such recommendations by clients.",

  Partners_3: "Partner's rights and obligations",
  ThePartner_3_1:
    "The Partner is obliged to attract new Customers to enter into brokerage service agreements with the Company and operate on international financial markets under the Company's terms and conditions.",
  ThePartner_3_2:
    "The Partner is obliged to open an affiliate account with the Company in order to receive commissions.",
  ThePartner_3_3:
    "The Partner is obliged to be competent about the Company’s services and master general information about international financial markets.",
  ThePartner_3_4:
    "The Partner is obliged to study all the Company’s informational resources on his own and inform Customers about important changes in a timely manner.",
  ThePartner_3_5:
    "The Partner is obliged to provide Customers in their affiliate group with comprehensive information and legal support, as well as solve problems Customers may face while trading on foreign exchange markets.",
  ThePartner_3_6:
    "The Partner is obliged to answer all Customer inquiries about the services provided by the Company since the Company does not have access to the management of the partner’s group.",
  ThePartner_3_7:
    "The Partner is not entitled to enter into any sub-agency and other agreements (contracts) which give a right to delegate the Partner’s authority, in full or in part, to third parties under the present Agreement without prior written consent from the Company. The assignment of right of demand is only possible after obtaining the Company’s consent.",
  ThePartner_3_8:
    "Should the Partner be incapable of solving the problem of a Customer on his own, the Partner is obliged to contact the Company’s specialists with all the details necessary to solve the problem (account numbers, order tickets, time of order, etc.).",
  ThePartner_3_9:
    "The Partner has a right to plan and implement marketing and advertising campaigns with help of the Company or without it.",
  ThePartner_3_10:
    "The Partner has a right to replenish the affiliate account and withdraw funds from it in  accordance with the Client Agreement.",
  ThePartner_3_11:
    "As stated in the Client Agreement, the affiliate account is available as a private customer account, i.e. the Partner has a right to carry out trading operations on the affiliate account. Due to rapid changes in the exchange rates of national currencies used by customers to replenish their trading accounts, the Company reserves the right to use an average of these exchange rates in settlements with partners.",
  ThePartner_3_12:
    "In case of any problems related to business running and rendering the Company’s services, the Partner shall contact the Company with details of a problem so that the Company can advise the Partner on time on possible solutions.",
  ThePartner_3_13:
    "The Partner shall only be entitled to conduct trading operations on a Customer’s trading account with the written permission of the Customer and with the permission of the Company.",
  ThePartner_3_14:
    "The Partner has a right to monitor the efficiency of promotional campaigns through custom affiliate codes and affiliate statistics provided by the Company.",
  ThePartner_3_15:
    "The Partner has a right to use the design of the Company’s brand production for advertising.",
  ThePartner_3_16:
    "The Partner has a right to refer to PAMM traders and earn commissions on their trades.",
  ThePartner_3_17:
    "The Partner has a right to refer to PAMM investors and earn a profit share that has been set by a PAMM trader in case the investment is profitable.",
  ThePartner_3_18:
    "The Partner is entitled to a free affiliate website with regularly updated content. The Partner will be able to give it a domain name. The latter is to be approved by the Company in advance.",
  Company_4: "Company's rights and obligations",
  TheCompany_4_1:
    "The Company is obliged to open trading accounts for Customers referred by the Partner in accordance with the Client Agreement.",
  TheCompany_4_2:
    "The Company shall enable Customers to conduct trading operations in the system by providing Customers with login credentials (username and password).",
  TheCompany_4_3:
    "The Company is obliged to maintain a comprehensive record of all operations made by Customers.",
  TheCompany_4_4:
    "The Company shall provide the Partner with information concerning the content of  agreements signed as well as the terms and conditions of Customer participation in foreign exchange trading.",
  TheCompany_4_5:
    "The Company is obliged to make payments to the Partner on the basis of a monthly income and expense sheet.",
  TheCompany_4_6:
    "The Company has a right to request the Partner to provide a full report on the course and results of his/her Customer acquisition campaigns.",

  TheCompany_4_7:
    "In the event that the Partner fails to perform any obligations under the present Agreement, the Company has a right to exclude Customers from his/her affiliate group.",
  TheCompany_4_8:
    "In the event that the Partner breaches or fails to perform any obligations under the present Agreement, the Company has a right to terminate the present Agreement at its sole discretion.",
  TheCompany_4_9:
    "The Company has a right to perform other actions stipulated in the present Agreement and its Appendices.",
  TheCompany_4_10:
    "The Company has a right to freeze your account and consequently close it if you do not have any activity within a period of 180 days since your account was last active.",
  Partners_5: "Partner's work principles and Customer acquisition",
  Partners_5_1:
    "The Partner has a right to create a website relevant to the Company's activities containing information about international financial markets and providing brokerage, dealer and investment services with regard to Chapter 3.",
  Partners_5_2:
    "A Customer is registered and referred to the affiliate group by either of the following methods: A Customer clicks on an affiliate link to the Company’s official website or requests affiliation when contacting Client support.",
  Partners_5_3:
    "A Customer may choose to decline the Partner’s services and opt for being serviced by the Company.",
  Partners_5_4:
    "With a view to prevent unfair competition, it is prohibited to move clients from one affiliate group to another, as well as to move present Customers to affiliate groups. This Clause of the present Agreement is to be also observed by present Customers opening new accounts with the Company with an aim to move them to affiliate groups. Note: A Customer may apply to the Company with explanations why he was moved to another affiliate group. The Company shall consider and deliver a decision on each application individually.",
  Partners_5_5:
    "The Partner shall not be entitled to receive affiliate commissions from his own accounts and those owned by his close relatives if the Partner is an individual; as well as from the private accounts of founders or accounts of their close relatives if the Partner is a legal entity.",
  Partners_5_6:
    "The Partner is prohibited from using unfair methods of attracting the Customers including but not limited to using any forms of forced redirecting of users to the websites of the Company and registering them in the affiliate group.",
  Dispute_6: "Dispute resolution",
  Dispute_6_1:
    "The Partner has a right to submit a claim with the Company within 5 working days of the date upon which the Partner became aware of any event or occurrence alleged to cause such a claim.",
  Dispute_6_2:
    "Any claim by the Partner against the Company shall be either written on paper and sent to the Company by post or emailed to one of the Company’s official email addresses specified on the Company’s website. Claims made in any other way (forum, telephone etc.) shall not be taken into consideration. Details of the claim can not be disclosed to the Partner until the investigation.",
  Dispute_6_3:
    "Each claim must contain the first and second name of the Partner/Partner’s company name; a description of the disputable situation; other dispute details that might contribute to the conflict’s resolution. The claim must not contain an emotional evaluation of the disputable situation, verbal abuse of the Company, or expletives.",
  Dispute_6_4:
    "The Company has a right to request a Customer/the Partner to provide any information necessary for the dispute’s resolution.",
  Dispute_6_5:
    "The Company, in the event that the Partner's claim is justified, satisfies the complaint solely on the accrual of the financial trading account Partner within one working day.",
  Dispute_6_6:
    "In case of claims that are not mentioned in this Agreement, the Company considers them relying on generally accepted market practices and internal policy of the Company.",
  Dispute_6_7:
    "Partner claim must contain: Partner’s full Name, account number, Date and time when the disputable situation occurred; The ticket of disputable order if it’s known; description of a claim without emotional connotation. Claim should be directed to the special department and their email dealer@zetradex.com",
  Dispute_6_8:
    "The Company has a right to request a Customer/the Partner to provide any information necessary for the dispute’s resolution.",
  Dispute_6_9:
    "The Company has a right to reject a claim if the provisions set out in Clauses 6.2, 6.3, 6.4, 7.2 and 7.3 have not been met.",
  Dispute_6_10:
    "The Company is obliged to examine the Partner’s claim, deliver a decision on the dispute with the shortest possible delay and email it to the Partner. The maximum period for dispute investigation allowed is 10 working days since the date the claim was filed.",

  Dispute_6_11:
    "Disputes concerning the interpretation or application of the present Agreement shall be settled by negotiation.",
  Dispute_6_12:
    "A dispute might be referred to arbitration under the dispute resolution procedure. A request for arbitration can be submitted in case the claim was not satisfied, or there was no response to the claim within the period specified in Clauses 6.5, 7.2 and 7.3 hereof.",
  Data_7: "Data exchange",
  Data_7_1:
    "The Company shall contact the Partner via the following means of communication: email, phone, post office, messengers, social network personal pages,  announcement in the appropriate section of the Company’s website.",
  Data_7_2:
    "The Partner may contact the Company using the means of communication listed in Clause 7.1.",
  Data_7_3:
    "Messages, documents, announcements, notifications, confirmations, reports etc. shall be deemed accepted by the opposite Party for a 3 hours after sending a message by email; 3 hours after sending a message by the trading terminal’s internal mail;  30 minutes after sending a message by messengers, social networks; right after a telephone conversation was finished; 7 calendar days after sending documents by post.",
  Confidential_8: "Confidential information",
  Confidential_8_1:
    "The Partner shall not be entitled to disclose information received from the Company during the cooperation and data the present Agreement contains throughout the period of validity of the present Agreement and within 5 years after its termination.",
  Confidential_8_2:
    "The Partner shall not be entitled to divulge confidential information concerning the  Company’s business and services to a rival third party.",
  Confidential_8_3:
    "The Parties shall ensure confidentiality of Customer personal and account data as well as details of trades conducted by Customers.",
  Incomes_9: "Incomes and mutual settlements",
  Incomes_9_1:
    "The Company pays affiliate commissions to the Partner in accordance with Chapter 1 of the present Agreement. Commissions shall not be more than 50% of the average equity value on all Customer accounts in the affiliate group for a reporting month. The average equity value is calculated as a sum of equity values on all Customer accounts at the beginning and at the end of each reporting month divided by 2.",
  Incomes_9_2:
    "When calculating commissions, the Company has a right not to take into consideration trades made by Customers as a result of the trading platform faults and exclude Customers  responsible for such trades from the affiliate group.",
  Incomes_9_3: "Partner’s commissions can be canceled in following cases:",
  Incomes_9_3_1:
    "In case of detection of orders on the account of the attracted Client that violate the general Terms and conditions, including cases when using forbidden trading strategies or manipulations with bonuses or Zetradex Loyalty program;",
  Incomes_9_3_2:
    "if Clients are found using strategies aimed at profiting from affiliate commissions and rebates to the detriment of primary trading (including, but not limited to, cases where the strategy is part of the overall Client and affiliate account strategy),",
  Incomes_9_3_3:
    "In case the registration data of the Partner coincides, in part or in full, with registration data of a Customer who belongs to the affiliate group,",
  Incomes_9_4:
    "The Company reserves the right to exclude Clients from the affiliate group in case of systematic violations described in the clause 9.3.",
  Incomes_9_5:
    "In case the account of a Customer belonging to the affiliate group and the affiliate account are found using the same IP address, the Company reserves the right to consider this coincidence as a ground to apply Clauses 5.5 and 9.3 of the present Agreement to the affiliate account in full measure.",
  Incomes_9_6:
    "In order to prevent dishonest attempts to obtain commissions from trades executed on the accounts of referred Customers or the accounts registered under assumed names yet managed by the Partner, the Company reserves the right not to pay affiliate commissions from trades which yield a profit lesser than 6 pips.",
  Incomes_9_7:
    "The Company may regard cases of violation of Clauses 3.1 and 5.4 of the present Agreement by the Partner as activity inconsistent with the affiliate program principles. Customers attracted by violating any of the clauses of the present Agreement shall be excluded from the affiliate group, and commissions derived from their trades shall be canceled in full.",
  Incomes_9_8:
    "Each month the Partner has a right to request that the Company checks the number of Customers referred and the number of Customer accounts, as well as to review the results of their trading operations.",
  Incomes_9_9:
    "A commission is credited to the affiliate account immediately after a referred Customer closes a trade. In case the accounts of the Partner and a Customer are based on different servers of the Company, an affiliate commission is credited the day after a Customer closes a trade.",
  Incomes_9_10:
    "The Company reserves the right not to pay a commission from trades the margin of which proceeds from the bonus funds of the bonus program participants. This clause is applicable to commissions that have already been credited. Such bonus program participants may be excluded from the affiliate group.",

  Incomes_9_11:
    "In case a Customer belonging to the affiliate group applied to the Company’s Dealing Department with a claim regarding an order from which the Partner received a commission, the Company reserves the right to cancel the affiliate commission in full.",
  Incomes_9_12:
    "In case the profit from a trade made by a Customer does not exceed 5 pips, the Company reserves the right to adjust the affiliate commissions the Partner received from such trades.",
  Incomes_9_13:
    "Should the total amount of affiliate commissions obtained from any trading account exceeds 50% of the total deposit made by a Customer to this account (for instance, if the total amount of affiliate commissions from a $1,000 Customer account is more than $500), the Company reserves the right to adjust the total amount of affiliate commissions so that it is not more than 50% of the total deposit.",
  Incomes_9_14:
    "The Parties undertake to calculate and pay their taxes and other third party fiscal duties independently.",
  Incomes_9_15:
    "Commission withdrawal shall be done within the term defined by the payment system,  however, in the case of commission from referrals that were deposited via credit cards and some other payment systems, the term might be extended up to 45 calendar days from the last replenishment through this particular system with a further extension possible if required. The Company shall duly inform the Partner of imposing such restrictions.",
  Incomes_9_16:
    "The company are eligible to identify accounts of partners by IP (matching at least 75%) or by other signs that would indicate on belonging of the group of accounts to one person, and based on that eligible to make appropriate financial corrections on every account in the group of account, in case of abuse with Company's services, fraudulent activity or systemic violation terms and conditions of the User/Partner agreement, in order to cover the negative consequences of such activities for the Company and other clients of the Company.",
  Incomes_9_17:
    "The Company shall pay the Partner affiliate commissions from all trades made by Customers referred by the Partner, regardless of the fact whether Customers gained any profit or not.",
  Incomes_9_18:
    "Affiliate commission amount is determined by current partner’s earnings rates and IB status ",
  Incomes_9_19:
    "Any other payments are possible only if the Company and the Partner have agreed on this in additional agreements and promotions",
  Final_10: "Final provisions",
  Final_10_1:
    "The present Agreement is enforced on the date when the last of the two Parties has duly signed it.",
  Final_10_2:
    "The present Agreement is valid for unlimited period until of parties declare their wish to cancel cooperation",
  Final_10_3:
    "The Company shall have the absolute discretion to amend and supplement any of the terms and conditions stipulated in the present Agreement.",
  Final_10_4:
    "Either Party may terminate the present Agreement unilaterally by giving at least 5 calendar days’ prior notice to the other Party.",
  Final_10_5:
    "Either Party is entitled to apply to court seeking to terminate the present Agreement in case of a repeated breach of obligations by the other Party as well as other cases specified in the current legislation.",
} as PartnershipAgreementType;
